name: PhatLootsQuests
version: 2.0
description: Quests module for PhatLoots
author: Browsit
website: https://github.com/Browsit/PhatLootsQuestsModule

main: org.browsit.phatlootsquests.PhatLootsModule
depend: [PhatLoots, Quests]